title: חד"ג
logo: /assets/img/phonto.png
email: github@hasidic.dev
description: Welcome to the HDG website, we hope you enjoy your stay, here are some handy links
show_downloads: true
google_analytics: G-RFZD80ETP9
color-scheme: auto
collections:
  authors:
    output: true
excerpt_separator: <!--more-->

domain: hasidic.dev
url: "https://hasidic.dev"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:

  - name: " Services"
    icon: <i class="fa-solid fa-network-wired"></i>
    link: /services

  - name: " Portfolio"
    icon: <i class="fa-solid fa-folder-open"></i>
    link: /portfolio

  - name: " Our Team"
    icon: <i class="fa-solid fa-building-shield"></i>
    link: /staff

  - name: " Our Blog"
    icon: <i class="fa-solid fa-pen"></i>
    link: /blog 

  - name: " Discord"
    icon: <i class="fa-brands fa-discord"></i>
    link: https://discord.gg/KpGXAEnVnv

  - name: " hasidicdevs"
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/hasidicdevs

  - name: " hasidicdevs"
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/hasidicdevs

#  - name: " Repositories"
#    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
#    link: https://github.com/hasidicdevs

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it

github: [metadata]