title: חד"ג
logo: /assets/img/phonto.png
email: github@hasidic.dev
description: Welcome to the HDG website, we hope you enjoy your stay, here are some handy links
show_downloads: true
google_analytics: G-RFZD80ETP9
color-scheme: auto
collections:
  authors:
    output: true
excerpt_separator: <!--more-->

domain: hasidic.dev
url: "https://hasidic.dev"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:

  - name: " Services"
    icon: <i class="fa-solid fa-network-wired"></i>
    link: /services

  - name: " Portfolio"
    icon: <i class="fa-solid fa-folder-open"></i>
    link: /portfolio

  - name: " Our Team"
    icon: <i class="fa-solid fa-building-shield"></i>
    link: /staff

  - name: " Our Blog"
    icon: <i class="fa-solid fa-pen"></i>
    link: /blog 

  - name: " Discord"
    icon: <i class="fa-brands fa-discord"></i>
    link: https://discord.gg/KpGXAEnVnv

  - name: " hasidicdevs"
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/hasidicdevs

  - name: " hasidicdevs"
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/hasidicdevs

toolbar:
  - name: "Pricing Tool"
    icon: 
    link: /pricing

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it

github: [metadata]