title: Hasidic Development Group
subtitle: Welcome to the HDG website, we are a web design startup and we look forward to working with you!
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Hasidic Development Group website, we hope you find everything you need...

url: "https://hasidic.dev" 
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    #- text: Gallery
    #  url: /gallery
    - text: Staff
      url: /staff
    - text: Services
      url: /services  
    #- text: Shop
    #  url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: phonto.png
author: "[hdg]"
author_bio: Welcome to the website for the “Hasidic Development Group” on discord and github. We are a group of developers who hang out on discord and code with one another. We are a small business startup providing web design services. We listen to music, chat about topics that interest us and welcome new people to join us in our journey as we code together. If you are looking for a web design or an application to be built you can find a description of our services we provide and the pricing models we use on the services page.
author_email: "github@hasidic.dev"
author_location: https://discord.gg/KpGXAEnVnv
author_website_url: "https://hasidic.dev"
typewrite-text: we are a web design startup and we look forward to working with you!
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences /APPS/
author_work_experiences:
            - company_name: hdg-bot
              company_logo: bot-discord.png
              company_url: https://github.com/hasidicdevs/hdg-bot
              designation: Discord Bot Base
              description: This is a simple discord bot building base for use in npm projects. It is available as an npm package in the npm package store. "npm install -g hdg-bot"
              visibility: true
            - company_name: hdg-md
              company_logo: markdown.png
              company_url: https://github.com/hasidicdevs/hdg-md
              designation: Markdown Viewer NPM package
              description: This is a simple markdown viewer package we wrote to assist on the tools we use. It is available in the npm package store as a download. "npm install -g hdg-md"
              visibility: true

# Education
author_education_details:
              - college_logo: edx.jpg
                college_name: MITx
                college_url: https://mit.org
                college_degree: MIT edX
                description: Course Completion Certificate
                visibility: true
              - college_logo: fcc.jpg
                college_name: FreeCodeCamp
                college_url: https://freecodecamp.org
                college_degree: Responsive Web Development 
                description: Course Completion Certificate
                visibility: true
              - college_logo: fcc.jpg
                college_name: FreeCodeCamp
                college_url: https://freecodecamp.org
                college_degree: JavaScript Data Structures & Algorithms 
                description: Course Completion Certificate
                visibility: true
              - college_logo: fcc.jpg
                college_name: FreeCodeCamp
                college_url: https://freecodecamp.org
                college_degree: Front End Development 
                description: Course Completion Certificate
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: ocebots.png
                project_title: Ocebots
                project_description: Website built for the Ocebots robotics department 
                project_url: https://Ocebots-Robotics.hasidicdev.repl.co
                visibility: true
              - project_thumbnail: quotes.png
                project_title: Random Quote Machine
                project_description: Random Quotes Generator in React.js
                project_url: https://idf5kq.csb.app/
                visibility: true
              - project_thumbnail: dhal.png
                project_title: Ryan Dhal - Tribute Page
                project_description: A simple tribute page built in html / css for Ryan Dhal, the man, the myth, the legend
                project_url: https://tribute-page.hasidicdev.repl.co/
                visibility: true
              - project_thumbnail: portfolio.png
                project_title: Yosi Leyid - Portfolio
                project_description: A Portfolio project for FreeCodeCamp
                project_url: https://portfolio.hasidicdev.repl.co/
                visibility: true


# social links
twitter_username: hasidicdevs
github_username:  hasidicdevs
facebook_username: 
linkedin_username: 
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: hasidicdevs
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: yosileyid

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 7814234c-6c50-42d5-9532-b62cac79c0c2
formspree_email: github@hasidic.dev

# releases - widget can be (sidebar, modal or embed)
olvy_organization: hasidicdevs
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
